"""create relationships

Revision ID: 8866d63084d8
Revises: 334bf5d4d4bd
Create Date: 2023-04-10 10:00:24.773983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8866d63084d8'
down_revision = '334bf5d4d4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True))

    with op.batch_alter_table('campers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('camper_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_signups_activity_id_activities'), 'activities', ['activity_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_signups_camper_id_campers'), 'campers', ['camper_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_signups_camper_id_campers'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_signups_activity_id_activities'), type_='foreignkey')
        batch_op.drop_column('activity_id')
        batch_op.drop_column('camper_id')
        batch_op.drop_column('time')

    with op.batch_alter_table('campers', schema=None) as batch_op:
        batch_op.drop_column('age')
        batch_op.drop_column('name')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('difficulty')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
